realm: playground
enabled: true
displayName: Rust Playground
loginWithEmailAllowed: true
registrationAllowed: true
loginTheme: keycloak
resetPasswordAllowed: true
accountTheme: keycloak.v2
emailTheme: keycloak
sslRequired: $(env:SSL_REQUIRED:-EXTERNAL)

eventsEnabled: true
# 120 days
eventsExpiration: 10368000

clientScopes:
  - name: custom.api
    description: Custom API Access
    protocol: openid-connect

clients:
  - clientId: web-frontend-spa
    protocol: openid-connect
    name: "Demo SPA Frontend"
    description: "Frontend SPA Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    # Show client in account-console
    alwaysDisplayInConsole: true
    serviceAccountsEnabled: false

    # Ask user for consent
    consentRequired: true

    #    attributes: { }
    fullScopeAllowed: false
    rootUrl: "https://apps.rust.test:4443/web-frontend-spa"
    baseUrl: "/?realm=playground&scope=openid"
    adminUrl: ""
    redirectUris:
      - "/*"
    webOrigins:
      - "+"
    defaultClientScopes:
      - "email"
    optionalClientScopes:
      - "phone"
      - "profile"
      - "custom.api"
    attributes:
    # Enable PKCE validation
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"


  - clientId: demo-confidential-standard-client
    protocol: openid-connect
    name: "Confidential Client with Standard Flow"
    description: "Standard Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    secret: secret
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/demo-standard-client/login*"
      - "https://flowsimulator.pragmaticwebsecurity.com/*"
    webOrigins:
      - "+"
    attributes:
      "post.logout.redirect.uris": "+"

  - clientId: demo-confidential-standard-client-with-pkce
    protocol: openid-connect
    name: "Confidential Client with Standard Flow + PKCE"
    description: "Standard Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    secret: secret
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/demo-standard-client/login*"
      - "https://flowsimulator.pragmaticwebsecurity.com/*"
    webOrigins:
      - "+"
    attributes:
      # enforce PKCE
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"


  - clientId: demo-public-client
    protocol: openid-connect
    name: "Public Client with Standard and Implicit Grant"
    description: "Public Client Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    implicitFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/demo-implcit-client/oauth/callback"
      - "https://flowsimulator.pragmaticwebsecurity.com/*"
    attributes:
      "post.logout.redirect.uris": "+"


  - clientId: demo-public-client-with-pkce
    protocol: openid-connect
    name: "Public Client with Standard and Implicit Grant"
    description: "Public Client Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: true
    implicitFlowEnabled: true
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    fullScopeAllowed: false
    redirectUris:
      - "http://localhost/demo-implcit-client/oauth/callback"
      - "https://flowsimulator.pragmaticwebsecurity.com/*"
    attributes:
      # enforce PKCE
      "pkce.code.challenge.method": "S256"
      "post.logout.redirect.uris": "+"

  - clientId: demo-public-client-ropc
    protocol: openid-connect
    name: "Public Client with ROPC Grant"
    description: "Direct Access Grant Client Description"
    enabled: true
    publicClient: true
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    fullScopeAllowed: false

  - clientId: demo-confidential-client-ropc
    protocol: openid-connect
    name: "Confidential Client with ROPC Grant"
    description: "Direct Access Grant Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: true
    serviceAccountsEnabled: false
    secret: secret
    fullScopeAllowed: false

  - clientId: demo-confidential-client-service
    protocol: openid-connect
    name: "Standard Client with Client Credentials Grant"
    description: "Service Client Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: true
    secret: secret
    fullScopeAllowed: false

  - clientId: demo-device-client
    protocol: openid-connect
    name: "Client with Device Flow Grant"
    description: "Device Flow Grant Description"
    enabled: true
    publicClient: false
    standardFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    secret: secret
    fullScopeAllowed: false
    attributes:
      "oauth2.device.authorization.grant.enabled": "true"
    redirectUris: []

roles:
  # Realm specific roles
  realm:
    - name: "user"
      description: "User Role"
    - name: "admin"
      description: "Admin Role"
    - name: "guest"
      description: "Guest Role"

groups:
  - "name": "Users"
    "attributes":
      groupAttribute1: ["groupAttributeValue1"]
    "realmRoles":
      - "user"
    #    "clientRoles": {}
    "subGroups": []

  - "name": "Admins"
  - "name": "Guests"

users:
  - username: tester
    email: test@local.test
    emailVerified: true
    firstName: Theo
    lastName: Tester
    enabled: true
    attributes:
      locale: [ "de" ]
      phoneNumber: [ "+49178111222333" ]
      phoneNumberVerified: [ "true" ]
    credentials:
      - type: password
        userLabel: initial
        value: test
        temporary: false
    realmRoles:
      - "user"
    groups:
      - "Users"
  - username: admin
    email: admin@local.test
    emailVerified: true
    firstName: Arno
    lastName: Admin
    enabled: true
    attributes:
      locale: [ "de" ]
    credentials:
      - type: password
        userLabel: initial
        value: test
        temporary: false
    realmRoles:
      - "admin"
    groups:
      - "Admins"
  - username: guest
    email: guest@local.test
    emailVerified: true
    firstName: Guido
    lastName: Guest
    enabled: true
    attributes:
      locale: [ "de" ]
    credentials:
      - type: password
        userLabel: initial
        value: test
        temporary: false
    realmRoles:
      - "guest"
    groups:
      - "Guests"
